### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vasyl-protsiv** [VasyaPRO/algorithms#6]
- [x] Binary search
- [x] Prime sieve
- [x] Implicit Treap
- [x] Disjoint set union
- [x] Prefix function
- [ ] Cycle detection
- [ ] Binary indexed tree
- [ ] Max flow
- [ ] Trie
- [ ] Suffix array
- [ ] Least common ancestor
- [ ] Dynamic connectivity
